///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardAdminModelData {
/*
{
  "TotalUserActive": 8,
  "TotalUserRequest": 0,
  "TotalPlta": 13,
  "TotalTurbineReport": 2
}
*/

  int? TotalUserActive;
  int? TotalUserRequest;
  int? TotalPlta;
  int? TotalTurbineReport;

  DashboardAdminModelData({
    this.TotalUserActive,
    this.TotalUserRequest,
    this.TotalPlta,
    this.TotalTurbineReport,
  });
  DashboardAdminModelData.fromJson(Map<String, dynamic> json) {
    TotalUserActive = json['TotalUserActive']?.toInt();
    TotalUserRequest = json['TotalUserRequest']?.toInt();
    TotalPlta = json['TotalPlta']?.toInt();
    TotalTurbineReport = json['TotalTurbineReport']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TotalUserActive'] = TotalUserActive;
    data['TotalUserRequest'] = TotalUserRequest;
    data['TotalPlta'] = TotalPlta;
    data['TotalTurbineReport'] = TotalTurbineReport;
    return data;
  }
}

class DashboardAdminModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan data dashboard",
  "Data": {
    "TotalUserActive": 8,
    "TotalUserRequest": 0,
    "TotalPlta": 13,
    "TotalTurbineReport": 2
  }
}
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  DashboardAdminModelData? Data;

  DashboardAdminModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  DashboardAdminModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? DashboardAdminModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
