///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GeneratePasswordModelData {
/*
{
  "Password": "y4IAm14QBx"
} 
*/

  String? Password;

  GeneratePasswordModelData({
    this.Password,
  });
  GeneratePasswordModelData.fromJson(Map<String, dynamic> json) {
    Password = json['Password']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Password'] = Password;
    return data;
  }
}

class GeneratePasswordModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil membuat password baru",
  "Data": {
    "Password": "y4IAm14QBx"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  GeneratePasswordModelData? Data;

  GeneratePasswordModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  GeneratePasswordModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null)
        ? GeneratePasswordModelData.fromJson(json['Data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
