///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListUserModelMeta {
/*
{
  "Next": "",
  "Prev": ""
}
*/

  String? Next;
  String? Prev;

  ListUserModelMeta({
    this.Next,
    this.Prev,
  });
  ListUserModelMeta.fromJson(Map<String, dynamic> json) {
    Next = json['Next']?.toString();
    Prev = json['Prev']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Next'] = Next;
    data['Prev'] = Prev;
    return data;
  }
}

class ListUserModelData {
/*
{
  "Id": "01J1WS49F046AT1MSV124HG9Y8",
  "Name": "name",
  "Division": "Engineer",
  "Status": "active"
}
*/

  String? Id;
  String? Name;
  String? Division;
  String? Status;

  ListUserModelData({
    this.Id,
    this.Name,
    this.Division,
    this.Status,
  });
  ListUserModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Division = json['Division']?.toString();
    Status = json['Status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Division'] = Division;
    data['Status'] = Status;
    return data;
  }
}

class ListUserModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua user",
  "Data": [
    {
      "Id": "01J1WS49F046AT1MSV124HG9Y8",
      "Name": "name",
      "Division": "Engineer",
      "Status": "active"
    }
  ],
  "Meta": {
    "Next": "",
    "Prev": ""
  }
}
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<ListUserModelData?>? Data;
  ListUserModelMeta? Meta;

  ListUserModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
    this.Meta,
  });
  ListUserModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <ListUserModelData>[];
      v.forEach((v) {
        arr0.add(ListUserModelData.fromJson(v));
      });
      Data = arr0;
    }
    Meta = (json['Meta'] != null) ? ListUserModelMeta.fromJson(json['Meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    if (Meta != null) {
      data['Meta'] = Meta!.toJson();
    }
    return data;
  }
}
