///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserListModelMeta {
/*
{
  "Next": "",
  "Prev": ""
} 
*/

  String? Next;
  String? Prev;

  UserListModelMeta({
    this.Next,
    this.Prev,
  });
  UserListModelMeta.fromJson(Map<String, dynamic> json) {
    Next = json['Next']?.toString();
    Prev = json['Prev']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Next'] = Next;
    data['Prev'] = Prev;
    return data;
  }
}

class UserListModelData {
/*
{
  "Id": "01J1WS49F046AT1MSV124HG9Y8",
  "Name": "name",
  "Division": "Devops",
  "Status": "active"
} 
*/

  String? Id;
  String? Name;
  String? Division;
  String? Status;

  UserListModelData({
    this.Id,
    this.Name,
    this.Division,
    this.Status,
  });
  UserListModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Division = json['Division']?.toString();
    Status = json['Status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Division'] = Division;
    data['Status'] = Status;
    return data;
  }
}

class UserListModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua user",
  "Data": [
    {
      "Id": "01J1WS49F046AT1MSV124HG9Y8",
      "Name": "name",
      "Division": "Devops",
      "Status": "active"
    }
  ],
  "Meta": {
    "Next": "",
    "Prev": ""
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<UserListModelData?>? Data;
  UserListModelMeta? Meta;

  UserListModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
    this.Meta,
  });

  UserListModel copyWith({
    bool? Success,
    int? StatusCode,
    String? Message,
    List<UserListModelData?>? Data,
    UserListModelMeta? Meta,
  }) =>
      UserListModel(
        Success: Success ?? this.Success,
        StatusCode: StatusCode ?? this.StatusCode,
        Message: Message ?? this.Message,
        Data: Data ?? this.Data,
        Meta: Meta ?? this.Meta,
      );

  UserListModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <UserListModelData>[];
      v.forEach((v) {
        arr0.add(UserListModelData.fromJson(v));
      });
      Data = arr0;
    }
    Meta = (json['Meta'] != null)
        ? UserListModelMeta.fromJson(json['Meta'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    if (Meta != null) {
      data['Meta'] = Meta!.toJson();
    }
    return data;
  }
}
