///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDetailModelData {
/*
{
  "Id": "01J43C21T51C8ZEY1AC0CX8EET",
  "Name": "nama7",
  "Username": "nama7",
  "Email": "nama7@yopmail.com",
  "Division": "Engineer",
  "Role": "user",
  "Status": "active",
  "RadiusStatus": true,
  "CreatedAt": "2024-07-31 10:06:39",
  "UpdatedAt": "2024-08-03 20:01:53"
} 
*/

  String? Id;
  String? Name;
  String? Username;
  String? Email;
  String? Phone;
  String? Division;
  String? Role;
  String? Status;
  bool? RadiusStatus;
  String? CreatedAt;
  String? UpdatedAt;

  UserDetailModelData({
    this.Id,
    this.Name,
    this.Username,
    this.Email,
    this.Phone,
    this.Division,
    this.Role,
    this.Status,
    this.RadiusStatus,
    this.CreatedAt,
    this.UpdatedAt,
  });
  UserDetailModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Username = json['Username']?.toString();
    Email = json['Email']?.toString();
    Phone = json['Phone']?.toString();
    Division = json['Division']?.toString();
    Role = json['Role']?.toString();
    Status = json['Status']?.toString();
    RadiusStatus = json['RadiusStatus'];
    CreatedAt = json['CreatedAt']?.toString();
    UpdatedAt = json['UpdatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Username'] = Username;
    data['Email'] = Email;
    data['Phone'] = Phone;
    data['Division'] = Division;
    data['Role'] = Role;
    data['Status'] = Status;
    data['RadiusStatus'] = RadiusStatus;
    data['CreatedAt'] = CreatedAt;
    data['UpdatedAt'] = UpdatedAt;
    return data;
  }
}

class UserDetailModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan user",
  "Data": {
    "Id": "01J43C21T51C8ZEY1AC0CX8EET",
    "Name": "nama7",
    "Username": "nama7",
    "Email": "nama7@yopmail.com",
    "Division": "Engineer",
    "Role": "user",
    "Status": "active",
    "RadiusStatus": true,
    "CreatedAt": "2024-07-31 10:06:39",
    "UpdatedAt": "2024-08-03 20:01:53"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  UserDetailModelData? Data;

  UserDetailModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  UserDetailModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null)
        ? UserDetailModelData.fromJson(json['Data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
