///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateUpdatePltaUnitParamUnits {
/*
{
  "Id": "01J4B268KF2PNMYVCJ8T12CEG8",
  "Name": "update",
  "status": false
} 
*/

  String? Id;
  String? Name;
  bool? status;

  CreateUpdatePltaUnitParamUnits({
    this.Id,
    this.Name,
    this.status,
  });
  CreateUpdatePltaUnitParamUnits.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['status'] = status;
    return data;
  }
}

class CreateUpdatePltaUnitParam {
/*
{
  "Units": [
    {
      "Id": "01J4B268KF2PNMYVCJ8T12CEG8",
      "Name": "update",
      "status": false
    }
  ]
} 
*/

  List<CreateUpdatePltaUnitParamUnits?>? Units;

  CreateUpdatePltaUnitParam({
    this.Units,
  });
  CreateUpdatePltaUnitParam.fromJson(Map<String, dynamic> json) {
    if (json['Units'] != null) {
      final v = json['Units'];
      final arr0 = <CreateUpdatePltaUnitParamUnits>[];
      v.forEach((v) {
        arr0.add(CreateUpdatePltaUnitParamUnits.fromJson(v));
      });
      Units = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Units != null) {
      final v = Units;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Units'] = arr0;
    }
    return data;
  }
}
