///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PltaListModelMeta {
/*
{
  "Next": "",
  "Prev": ""
} 
*/

  String? Next;
  String? Prev;

  PltaListModelMeta({
    this.Next,
    this.Prev,
  });
  PltaListModelMeta.fromJson(Map<String, dynamic> json) {
    Next = json['Next']?.toString();
    Prev = json['Prev']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Next'] = Next;
    data['Prev'] = Prev;
    return data;
  }
}

class PltaListModelData {
/*
{
  "Id": "01J4B2TGE9TEH97X27SJB65BT1",
  "Name": "PLTA Kebumen 1",
  "Status": true,
  "CreatedAt": "2024-08-03 09:59:10",
  "CreatedBy": "aditya fullname"
} 
*/

  String? Id;
  String? Name;
  bool? Status;
  String? CreatedAt;
  String? CreatedBy;

  PltaListModelData({
    this.Id,
    this.Name,
    this.Status,
    this.CreatedAt,
    this.CreatedBy,
  });
  PltaListModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Status = json['Status'];
    CreatedAt = json['CreatedAt']?.toString();
    CreatedBy = json['CreatedBy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Status'] = Status;
    data['CreatedAt'] = CreatedAt;
    data['CreatedBy'] = CreatedBy;
    return data;
  }
}

class PltaListModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua plta",
  "Data": [
    {
      "Id": "01J4B2TGE9TEH97X27SJB65BT1",
      "Name": "PLTA Kebumen 1",
      "Status": true,
      "CreatedAt": "2024-08-03 09:59:10",
      "CreatedBy": "aditya fullname"
    }
  ],
  "Meta": {
    "Next": "",
    "Prev": ""
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<PltaListModelData?>? Data;
  PltaListModelMeta? Meta;

  PltaListModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
    this.Meta,
  });
  PltaListModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <PltaListModelData>[];
      v.forEach((v) {
        arr0.add(PltaListModelData.fromJson(v));
      });
      Data = arr0;
    }
    Meta = (json['Meta'] != null)
        ? PltaListModelMeta.fromJson(json['Meta'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    if (Meta != null) {
      data['Meta'] = Meta!.toJson();
    }
    return data;
  }
}
