///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PltaModelData {
/*
{
  "Id": "01J4BNVANWTPB4ZNWC0FQAAMMQ",
  "Name": "PLTA Radius - Unit 4",
  "Long": 12,
  "Lat": 32,
  "RadiusStatus": false,
  "Radius": 10,
  "RadiusType": "kilometer"
} 
*/

  String? Id;
  String? Name;
  int? Long;
  int? Lat;
  bool? RadiusStatus;
  int? Radius;
  String? RadiusType;

  PltaModelData({
    this.Id,
    this.Name,
    this.Long,
    this.Lat,
    this.RadiusStatus,
    this.Radius,
    this.RadiusType,
  });
  PltaModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Long = json['Long']?.toInt();
    Lat = json['Lat']?.toInt();
    RadiusStatus = json['RadiusStatus'];
    Radius = json['Radius']?.toInt();
    RadiusType = json['RadiusType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Long'] = Long;
    data['Lat'] = Lat;
    data['RadiusStatus'] = RadiusStatus;
    data['Radius'] = Radius;
    data['RadiusType'] = RadiusType;
    return data;
  }
}

class PltaModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua plta master",
  "Data": [
    {
      "Id": "01J4BNVANWTPB4ZNWC0FQAAMMQ",
      "Name": "PLTA Radius - Unit 4",
      "Long": 12,
      "Lat": 32,
      "RadiusStatus": false,
      "Radius": 10,
      "RadiusType": "kilometer"
    }
  ]
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<PltaModelData?>? Data;

  PltaModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  PltaModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <PltaModelData>[];
      v.forEach((v) {
        arr0.add(PltaModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
