///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PltaDetailModelDataUnits {
/*
{
  "Id": "01J4BNVANWTPB4ZNWC0909XJ2B",
  "Name": "1",
  "Status": true
} 
*/

  String? Id;
  String? Name;
  bool? Status;

  PltaDetailModelDataUnits({
    this.Id,
    this.Name,
    this.Status,
  });
  PltaDetailModelDataUnits.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Status = json['Status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, String>{};
    data['Id'] = Id ?? '';
    data['Name'] = Name ?? '';
    data['Status'] = '${Status ?? false}';
    return data;
  }
}

class PltaDetailModelData {
/*
{
  "Id": "01J4BNVANWTPB4ZNWC07SBPN13",
  "Name": "PLTA Radius",
  "Status": true,
  "Long": 12,
  "Lat": 32,
  "RadiusStatus": false,
  "Radius": 4,
  "RadiusType": "meter",
  "CreatedAt": "2024-08-03 15:31:40",
  "CreatedBy": "aditya fullname",
  "UpdatedAt": "",
  "UpdatedBy": "",
  "Units": [
    {
      "Id": "01J4BNVANWTPB4ZNWC0909XJ2B",
      "Name": "1",
      "Status": true
    }
  ]
} 
*/

  String? Id;
  String? Name;
  bool? Status;
  int? Long;
  int? Lat;
  bool? RadiusStatus;
  int? Radius;
  String? RadiusType;
  String? CreatedAt;
  String? CreatedBy;
  String? UpdatedAt;
  String? UpdatedBy;
  List<PltaDetailModelDataUnits?>? Units;

  PltaDetailModelData({
    this.Id,
    this.Name,
    this.Status,
    this.Long,
    this.Lat,
    this.RadiusStatus,
    this.Radius,
    this.RadiusType,
    this.CreatedAt,
    this.CreatedBy,
    this.UpdatedAt,
    this.UpdatedBy,
    this.Units,
  });
  PltaDetailModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Status = json['Status'];
    Long = json['Long']?.toInt();
    Lat = json['Lat']?.toInt();
    RadiusStatus = json['RadiusStatus'];
    Radius = json['Radius']?.toInt();
    RadiusType = json['RadiusType']?.toString();
    CreatedAt = json['CreatedAt']?.toString();
    CreatedBy = json['CreatedBy']?.toString();
    UpdatedAt = json['UpdatedAt']?.toString();
    UpdatedBy = json['UpdatedBy']?.toString();
    if (json['Units'] != null) {
      final v = json['Units'];
      final arr0 = <PltaDetailModelDataUnits>[];
      v.forEach((v) {
        arr0.add(PltaDetailModelDataUnits.fromJson(v));
      });
      Units = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Status'] = Status;
    data['Long'] = Long;
    data['Lat'] = Lat;
    data['RadiusStatus'] = RadiusStatus;
    data['Radius'] = Radius;
    data['RadiusType'] = RadiusType;
    data['CreatedAt'] = CreatedAt;
    data['CreatedBy'] = CreatedBy;
    data['UpdatedAt'] = UpdatedAt;
    data['UpdatedBy'] = UpdatedBy;
    if (Units != null) {
      final v = Units;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Units'] = arr0;
    }
    return data;
  }

  Map<String, dynamic> toJson2() => {
        "Units": Units == null
            ? []

            // "Units":
            //     Units == null ? [] : (Units ?? []).map((x) => x?.toJson()).toList(),
            : List<dynamic>.from((Units ?? []).map((x) => x?.toJson())),
      };
}

class PltaDetailModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan plta",
  "Data": {
    "Id": "01J4BNVANWTPB4ZNWC07SBPN13",
    "Name": "PLTA Radius",
    "Status": true,
    "Long": 12,
    "Lat": 32,
    "RadiusStatus": false,
    "Radius": 4,
    "RadiusType": "meter",
    "CreatedAt": "2024-08-03 15:31:40",
    "CreatedBy": "aditya fullname",
    "UpdatedAt": "",
    "UpdatedBy": "",
    "Units": [
      {
        "Id": "01J4BNVANWTPB4ZNWC0909XJ2B",
        "Name": "1",
        "Status": true
      }
    ]
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  PltaDetailModelData? Data;

  PltaDetailModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  PltaDetailModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null)
        ? PltaDetailModelData.fromJson(json['Data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
