import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateDataParamDataTurbine {
/*
{
  "A": [
    50
  ],
  "B": [
    42
  ],
  "C": [
    48
  ],
  "D": [
    40.5
  ]
} 
*/

  List<double?>? A;
  List<double?>? B;
  List<double?>? C;
  List<double?>? D;

  CreateDataParamDataTurbine({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  CreateDataParamDataTurbine.fromJson(Map<String, dynamic> json) {
    if (json['A'] != null) {
      final v = json['A'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      A = arr0;
    }
    if (json['B'] != null) {
      final v = json['B'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      B = arr0;
    }
    if (json['C'] != null) {
      final v = json['C'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      C = arr0;
    }
    if (json['D'] != null) {
      final v = json['D'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      D = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      final v = A;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['A'] = arr0;
    }
    if (B != null) {
      final v = B;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['B'] = arr0;
    }
    if (C != null) {
      final v = C;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['C'] = arr0;
    }
    if (D != null) {
      final v = D;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['D'] = arr0;
    }
    return data;
  }
}

class CreateDataParamDataClutch {
/*
{
  "A": [
    50
  ],
  "B": [
    46
  ],
  "C": [
    46
  ],
  "D": [
    51
  ]
} 
*/

  List<double?>? A;
  List<double?>? B;
  List<double?>? C;
  List<double?>? D;

  CreateDataParamDataClutch({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  CreateDataParamDataClutch.fromJson(Map<String, dynamic> json) {
    if (json['A'] != null) {
      final v = json['A'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      A = arr0;
    }
    if (json['B'] != null) {
      final v = json['B'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      B = arr0;
    }
    if (json['C'] != null) {
      final v = json['C'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      C = arr0;
    }
    if (json['D'] != null) {
      final v = json['D'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      D = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      final v = A;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['A'] = arr0;
    }
    if (B != null) {
      final v = B;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['B'] = arr0;
    }
    if (C != null) {
      final v = C;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['C'] = arr0;
    }
    if (D != null) {
      final v = D;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['D'] = arr0;
    }
    return data;
  }
}

class CreateDataParamDataUpper {
/*
{
  "A": [
    50
  ],
  "B": [
    48
  ],
  "C": [
    46
  ],
  "D": [
    55
  ]
} 
*/

  List<double?>? A;
  List<double?>? B;
  List<double?>? C;
  List<double?>? D;

  CreateDataParamDataUpper({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  CreateDataParamDataUpper.fromJson(Map<String, dynamic> json) {
    if (json['A'] != null) {
      final v = json['A'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      A = arr0;
    }
    if (json['B'] != null) {
      final v = json['B'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      B = arr0;
    }
    if (json['C'] != null) {
      final v = json['C'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      C = arr0;
    }
    if (json['D'] != null) {
      final v = json['D'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      D = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      final v = A;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['A'] = arr0;
    }
    if (B != null) {
      final v = B;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['B'] = arr0;
    }
    if (C != null) {
      final v = C;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['C'] = arr0;
    }
    if (D != null) {
      final v = D;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['D'] = arr0;
    }
    return data;
  }
}

class CreateDataParamData {
/*
{
  "Upper": {
    "A": [
      50
    ],
    "B": [
      48
    ],
    "C": [
      46
    ],
    "D": [
      55
    ]
  },
  "Clutch": {
    "A": [
      50
    ],
    "B": [
      46
    ],
    "C": [
      46
    ],
    "D": [
      51
    ]
  },
  "Turbine": {
    "A": [
      50
    ],
    "B": [
      42
    ],
    "C": [
      48
    ],
    "D": [
      40.5
    ]
  }
} 
*/

  CreateDataParamDataUpper? Upper;
  CreateDataParamDataClutch? Clutch;
  CreateDataParamDataTurbine? Turbine;

  CreateDataParamData({
    this.Upper,
    this.Clutch,
    this.Turbine,
  });
  CreateDataParamData.fromJson(Map<String, dynamic> json) {
    Upper = (json['Upper'] != null)
        ? CreateDataParamDataUpper.fromJson(json['Upper'])
        : null;
    Clutch = (json['Clutch'] != null)
        ? CreateDataParamDataClutch.fromJson(json['Clutch'])
        : null;
    Turbine = (json['Turbine'] != null)
        ? CreateDataParamDataTurbine.fromJson(json['Turbine'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Upper != null) {
      data['Upper'] = Upper!.toJson();
    }
    if (Clutch != null) {
      data['Clutch'] = Clutch!.toJson();
    }
    if (Turbine != null) {
      data['Turbine'] = Turbine!.toJson();
    }
    return data;
  }
}

class CreateDataParam {
/*
{
  "TowerId": "01J06EX7EJHFXC47Y6AE8SSPTC",
  "GenBearingToCoupling": 440,
  "CouplingToTurbine": 424,
  "TotalBolts": 8,
  "CurrentTorque": 400,
  "MaxTorque": 500,
  "Data": {
    "Upper": {
      "A": [
        50
      ],
      "B": [
        48
      ],
      "C": [
        46
      ],
      "D": [
        55
      ]
    },
    "Clutch": {
      "A": [
        50
      ],
      "B": [
        46
      ],
      "C": [
        46
      ],
      "D": [
        51
      ]
    },
    "Turbine": {
      "A": [
        50
      ],
      "B": [
        42
      ],
      "C": [
        48
      ],
      "D": [
        40.5
      ]
    }
  }
} 
*/

  String? TowerId;
  String? GenBearingToCoupling;
  String? CouplingToTurbine;
  String? TotalBolts;
  String? CurrentTorque;
  String? MaxTorque;
  CreateDataParamData? Data;

  CreateDataParam({
    this.TowerId,
    this.GenBearingToCoupling,
    this.CouplingToTurbine,
    this.TotalBolts,
    this.CurrentTorque,
    this.MaxTorque,
    this.Data,
  });
  CreateDataParam.fromJson(Map<String, dynamic> json) {
    TowerId = json['TowerId']?.toString();
    GenBearingToCoupling = json['GenBearingToCoupling'];
    CouplingToTurbine = json['CouplingToTurbine'];
    TotalBolts = json['TotalBolts'];
    CurrentTorque = json['CurrentTorque'];
    MaxTorque = json['MaxTorque'];
    Data = (json['Data'] != null)
        ? CreateDataParamData.fromJson(jsonDecode(json['Data']))
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, String>{};
    data['TowerId'] = TowerId ?? '';
    data['GenBearingToCoupling'] = GenBearingToCoupling ?? '';
    data['CouplingToTurbine'] = CouplingToTurbine ?? '';
    data['TotalBolts'] = TotalBolts ?? '';
    data['CurrentTorque'] = CurrentTorque ?? '';
    data['MaxTorque'] = MaxTorque ?? '';
    if (Data != null) {
      data['Data'] = jsonEncode(Data?.toJson());
    }
    return data;
  }
}
