///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "Name": "aditya fullname",
  "Division": "Engineer",
  "Source": "main",
  "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjI3NzYzNTcsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.UP72sZL02uynGNnJBbQqJ9qxWktvKR1DV-GpKttwJtpc8kfFRCqgRGIEq7qReGVCFCWSgu4N2bwz1T5AzfsNdddmdfyZLLGEKr8goLHJcQdpmsRLtffp56JA-_OmGUos9EKMsrKzIQ-aOrJRvskfvJU3HXfNw41P38XRq6SAoN4",
  "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjI2OTA1NTcsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.VpcCFDkg3_U4qTsKsHxQP16hoNjLNTpDEws3AxIVVa5JAb7EhcbPTG6v9YysI2AsVYIyx73FguzI3U5besJ-xMuvOj8yCjq29frJN9Tr0GR18FCShVSFC89rMO0UnTkRqmxmjwiIchtKGAFgxejx8jHqmZgE30M0B7IaDO8s2SU"
} 
*/

  String? Name;
  String? Division;
  String? Source;
  String? Token;
  String? RefreshToken;

  LoginModelData({
    this.Name,
    this.Division,
    this.Source,
    this.Token,
    this.RefreshToken,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    Division = json['Division']?.toString();
    Source = json['Source']?.toString();
    Token = json['Token']?.toString();
    RefreshToken = json['RefreshToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['Division'] = Division;
    data['Source'] = Source;
    data['Token'] = Token;
    data['RefreshToken'] = RefreshToken;
    return data;
  }
}

class LoginModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil login",
  "Data": {
    "Name": "aditya fullname",
    "Division": "Engineer",
    "Source": "main",
    "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjI3NzYzNTcsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.UP72sZL02uynGNnJBbQqJ9qxWktvKR1DV-GpKttwJtpc8kfFRCqgRGIEq7qReGVCFCWSgu4N2bwz1T5AzfsNdddmdfyZLLGEKr8goLHJcQdpmsRLtffp56JA-_OmGUos9EKMsrKzIQ-aOrJRvskfvJU3HXfNw41P38XRq6SAoN4",
    "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjI2OTA1NTcsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.VpcCFDkg3_U4qTsKsHxQP16hoNjLNTpDEws3AxIVVa5JAb7EhcbPTG6v9YysI2AsVYIyx73FguzI3U5besJ-xMuvOj8yCjq29frJN9Tr0GR18FCShVSFC89rMO0UnTkRqmxmjwiIchtKGAFgxejx8jHqmZgE30M0B7IaDO8s2SU"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  LoginModelData? Data;

  LoginModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? LoginModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
