///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "Name": "aditya fullname",
  "Division": "Engineer",
  "IsAdmin": true,
  "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjE2NDI0MDIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.RK8kzzJlKeCMX_h2sBpn1EE103svfk6va6UYFZ19epG-2uVs5Lt2SjIaED0Lid4VkAlFiZvJpJRuHnoWzjqgiuUJNTYexNzCA83CiP6-1oy36gCIhcZo44Tzhc74-hm9eAHlvUMSjiF7IS-ZbbbkPx566TCCGMa-ZG15k62JU8Q",
  "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjE1NTY2MDIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.SkKmI2Yu5AT2nG3H_TP-P_4jn1tg7uju_Vm1og79zeO1R9kNPBWVfYwy4gh40IxJyFYlhfqOcCHuLK6vZkNN_A5KgM8iINIX0YllWV0n5BTN0HonIclcoAwE49seqE1nhnQfQudEFcE7yWeM2Y5UqYOd0wC1m6VbaUaOJkt142A"
}
*/

  String? Name;
  String? Division;
  bool? IsAdmin;
  String? Token;
  String? RefreshToken;

  LoginModelData({
    this.Name,
    this.Division,
    this.IsAdmin,
    this.Token,
    this.RefreshToken,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    Division = json['Division']?.toString();
    IsAdmin = json['IsAdmin'];
    Token = json['Token']?.toString();
    RefreshToken = json['RefreshToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['Division'] = Division;
    data['IsAdmin'] = IsAdmin;
    data['Token'] = Token;
    data['RefreshToken'] = RefreshToken;
    return data;
  }
}

class LoginModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil login",
  "Data": {
    "Name": "aditya fullname",
    "Division": "Engineer",
    "IsAdmin": true,
    "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjE2NDI0MDIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.RK8kzzJlKeCMX_h2sBpn1EE103svfk6va6UYFZ19epG-2uVs5Lt2SjIaED0Lid4VkAlFiZvJpJRuHnoWzjqgiuUJNTYexNzCA83CiP6-1oy36gCIhcZo44Tzhc74-hm9eAHlvUMSjiF7IS-ZbbbkPx566TCCGMa-ZG15k62JU8Q",
    "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MjE1NTY2MDIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.SkKmI2Yu5AT2nG3H_TP-P_4jn1tg7uju_Vm1og79zeO1R9kNPBWVfYwy4gh40IxJyFYlhfqOcCHuLK6vZkNN_A5KgM8iINIX0YllWV0n5BTN0HonIclcoAwE49seqE1nhnQfQudEFcE7yWeM2Y5UqYOd0wC1m6VbaUaOJkt142A"
  }
}
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  LoginModelData? Data;

  LoginModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? LoginModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
